name: Azure deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # adjust this to your project's Node.js version

    # - name: Install dependencies at Frontend and Move to public folder
    #   run: chmod +x ./script.sh && ./script.sh

    # - name: Move build folder
    #   run: mv ./web/build ./backend/public
    
    - name: Install dependencies at Backend
      working-directory: ./backend
      run: npm install

    # - name: Build
    #   working-directory: ./backend
    #   run: npm run build  # adjust this if your build command is different
  
    - name: Deploy to Azure App Service (Node-Backend)
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.AZURE_APP_NAME }}' # replace this with your App Service's name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Azure App Service publish profile, stored as a GitHub secret
        package: './backend' # path to the built app's directory
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install pip with py-ai
      working-directory: ./py-ai
      run: pip install -r requirements.txt

     - name: Deploy to Azure App Service (Python-AI)
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{ secrets.AZURE_APP_NAME_PYTHON }}' # replace this with your App Service's name for the Python app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PYTHON }} # Azure App Service publish profile for the Python app, stored as a GitHub secret
        package: './py-ai' # path to the Python app's directory